name: CD / Publish / Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag nextris:${{ github.run_number }}

      - name: Stop and remove existing container
        run: |
          docker stop nextris || true
          docker rm nextris || true

      - name: Remove previous image
        run: docker rmi $(docker images -q nextris:$(expr ${{ github.run_number }} - 1)) || true

      - name: Run Docker container
        run: docker run -d -p 1504:3000 --name nextris nextris:${{ github.run_number }}
